name: gemini_dart
description: A comprehensive Dart package for integrating Google's Gemini AI models with support for text, image, and video processing.
version: 0.1.1
homepage: https://github.com/abdallahshaban557/gemini_dart
repository: https://github.com/abdallahshaban557/gemini_dart
issue_tracker: https://github.com/abdallahshaban557/gemini_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.2
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.7
  lints: ^3.0.0
  mockito: ^5.4.2
  test: ^1.24.0
