name: gemini_dart
description: A comprehensive Dart package for integrating Google's Gemini AI models with support for text, image, and video processing.
version: 0.1.0
homepage: https://github.com/your-username/gemini_dart
repository: https://github.com/your-username/gemini_dart
issue_tracker: https://github.com/your-username/gemini_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.0

flutter:
  # This package contains Flutter widgets
  plugin:
    platforms:
      android:
        package: com.example.gemini_dart
        pluginClass: GeminiDartPlugin
      ios:
        pluginClass: GeminiDartPlugin
